version: '3'
services:
  postgres:
    image: 'postgres:14'
    container_name: 'lunii-api-server-postgres'
    volumes:
      - './local/docker/postgresql:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
